### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by radville** [Ammar-Raneez/SDGP-ONCO#56]
In Community Exchange, GitHub Topics will help the discoverability of your project. You've already done a great job of adding topics related to the tech stack you used in this project! I recommend adding a few more topics for discoverability, including:

* the subject matter of your repo
* the subject(s) covered in your `LEARN.md`

There is a limit of 20 topics you can add to your repo. We recommend under 10 topics, so you might consider removing some of the topics related to tech stack when you add topics related to the `Learn.md` and the cancer prognosis/subject matter topics.

**Comment by Ammar-Raneez** [comment]
Have updated 😄
