### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by radville** [Ammar-Raneez/SDGP-ONCO#57]
A README is often the first item a visitor will see when visiting your repository. Your README already describes the purpose of the repo really well. We recommend that your README also includes information on:

- [ ] How users can get started with the project
  * Explain to users that there is a LEARN.md
- [ ] Mention your code of conduct
- [ ] Describe who maintains the project and who can contribute to it

**Comment by Ammar-Raneez** [comment]
Have put up a PR 😄
