### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by radville** [Ammar-Raneez/SDGP-ONCO#58]
Other than GitHub Topics, your description will be the primary way of catching the users eyes. Your repo description should be clear and concise. Ask yourself:

* In one sentence, how do I convey what my repo does?
* What type of users am I interested in attracting to my repo?
* If I was a user, what words or phrases might spark my interest?

I recommend adding a little more information to your description that gives a bit more information to users 😄

**Comment by Ammar-Raneez** [comment]
Have updated 😄

**Comment by radville** [comment]
Perfect - looks good!
